server:
  port: 80


spring:
  application:
    name: mbx-message
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource            # 当前数据源操作类型
    driver-class-name: com.mysql.jdbc.Driver          # mysql驱动包
    url: jdbc:mysql://114.55.27.239:3306/sygl?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 565977989
mybatis:
  mapperLocations: classpath:mapper/*.xml
  type-aliases-package: com.maboxuan.entities    # 所有Entity别名类所在包